### ISSUE TITLE
http.Response.Body is truncated on the right

### ISSUE THREAD

**Issue by felicson** [henvic/httpretty#15]
Hi. Thanks for the library. 
I noticed one point, it's looks like a bug or unexpected behavior.
This code is truncates the http response body that is used for http the response consumer https://github.com/henvic/httpretty/blob/main/printer.go#L276 and breaks the response.
Is this a bug or not?

**Comment by henvic** [comment]
Thank you, @felicson and @mislav! Fixed. Sorry for taking too long to respond.
