### ISSUE TITLE
Let user hide unwanted headers

### ISSUE THREAD

**Issue by henvic** [henvic/httpretty#3]
On https://github.com/cli/cli/pull/306#pullrequestreview-361869659 @mislav asked me for

> a way to avoid certain request/response headers being printed; perhaps accept a func that takes a header name and returns a boolean that indicates whether to print or not?

This might be achieved with a function similar to SetFilter and SetBodyFilter. It might take a slice and store the data in a `map[string]struct{}` to be checked when printing headers.

Probably can be called `FilterHeader` or `FilterHeaders`.

**Comment by mislav** [comment]
🎉
