### ISSUE TITLE
Request path interpreted as format string

### ISSUE THREAD

**Issue by mislav** [henvic/httpretty#9]
Making a request with a query parameter with value `foo & bar` results in something like this being printed:

```
> POST /mypath?label=foo+%!+(MISSING)bar HTTP/1.1
```

This is because the `&` character gets %-encoded when in a URL, and `color.Format()` interprets anything passed to it as a format string. Any value that could potentially have a literal `%` character in it (any dynamic or user-defined value, really) should never be used a sprintf format string.

**Comment by henvic** [comment]
Hello @mislav,

Thanks for the report!

Sorry for not answering you before. I missed this notification :|
/Thanks @pragmaticivan for showing me this issue.

I released a new v0.0.6 version with a fix for this.

You can see the changes at https://github.com/henvic/httpretty/pull/10
